services:
  model:
    image: model
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m jupyter notebook --ip 0.0.0.0 --no-browser --allow-root
    ports:
      - "8888:8888"    
    volumes:
      - ../inference/models:/models/
      - ../datasets:/datasets
      - ../code/utils:/model/utils/
      - ../code/1_baseline:/model/1_baseline/
      - ../code/2_kg_inference:/model/2_kg_inference/
      - ../code/3_link_prediction:/model/3_link_prediction/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
# watch -n 0.5 nvidia-smi 